name: CI for React (Vite)

on:
  push:
    branches:
      - main  # Ejecutar en cada push a la rama 'main'
  pull_request:
    branches:
      - main  # Ejecutar también en cada pull request hacia 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos una máquina virtual de Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Usamos Node.js versión 16

      - name: Install dependencies
        run: npm install  # Instalar las dependencias

      - name: Run tests
        run: npm test -- --coverage  # Ejecutar pruebas, si las tienes configuradas

      - name: Build the project
        run: npm run build  # Construir el proyecto si lo necesitas
